In [9]:
import numpy as np
import statistics as st

In [4]:
np.array([1,2])

array([1, 2])

In [5]:
print(np.array([1,2]))

[1 2]


In [8]:
print(np.array([[1,2], [3,4], [5,6]]))

[[1 2]
 [3 4]
 [5 6]]


In [14]:
marks = np.array([[78,67,90],[34,55,23],[12,90,45]])

In [15]:
st.mode(marks.flatten())

90

In [16]:
my_arr = np.array([[i for i in range(4)] for _ in range(4)])

In [18]:
my_arr.ndim

2

In [20]:
my_arr

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])