In [1]:
import numpy as np
import statistics as st

In [4]:
np.array([1,2])

array([1, 2])

In [5]:
print(np.array([1,2]))

[1 2]


In [8]:
print(np.array([[1,2], [3,4], [5,6]]))

[[1 2]
 [3 4]
 [5 6]]


In [14]:
marks = np.array([[78,67,90],[34,55,23],[12,90,45]])

In [15]:
st.mode(marks.flatten())

90

In [16]:
my_arr = np.array([[i for i in range(4)] for _ in range(4)])

In [18]:
my_arr.ndim

2

In [20]:
my_arr

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [1]:
# 2d array: [2][3] => you want 2 one dimension arrays, each with 3 elements
    # one dimensional arrays are the rows
# 3d array: [2][3][3] => you want 2 two dimension arrays, each of them a 3*3 2d array
    # two dimensional arrays are the rows

In [6]:
davids_marks = np.array([
    [78, 67, 90],
    [34, 55, 23],
    [12, 89, 45]
])

In [2]:
arr = np.array([i+1 for i in range(12)])
print(arr)
# [ 1  2  3  4  5  6  7  8  9 10 11 12]
# [[1, 2, 3],[4, 5, 6],[7, 8, 9],[10, 11, 12]]
# [[1, 2, 3, 4, 5, 6],[7, 8, 9, 10, 11, 12]]
arr = arr.reshape(4, 3)
print(arr)
arr = arr.reshape(2, 6)
print(arr)
# two arrays -> three arrays -> elements
# [[[1, 2], [3, 4], [5, 6]],[[7, 8], [9, 10], [11, 12]]]
arr = arr.reshape(2, 3, 2)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [3]:
arr = np.array([[[1], [2], [3], [4]],[[5], [6], [7], [8]],[[9], [10], [11], [12]]])
print(arr.ndim)

3
