In [16]:
import numpy as np
import statistics as st

In [7]:
# number 1

# c = [5 7 9]

In [18]:
# number 2

arr = np.array([0 for _ in range(10)])
arr = arr.reshape(2,5)
arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [23]:
# number 3

data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

print(np.mean(data))
print(np.median(data))
print(np.std(data))
print(st.mode(data))

10.5
10.5
5.766281297335398
1


In [45]:
# number 4
from random import randint
arr = np.array([[randint(1,30) for _ in range(6)] for _ in range(6)])
print(arr)
print(np.max(arr))
print(np.min(arr))

[[ 4 22 10 14  5 17]
 [11  6 27 30 27 16]
 [11  7 19  8 12 10]
 [30  7 24 25 29  7]
 [20 27 22 25  1 21]
 [ 1 11 28 30 19 23]]
30
1


In [54]:
# number 5

arr = np.array( [[[ 5,  4],
      [ 6,  9]],
 
      [[ 1,  0],
      [ 9,  5]],
 
      [[ 4,  9],
      [13, 19]],
                  
      [[ 8, 10],
      [ 1, 5]]])
arr.reshape(4,4)

array([[ 5,  4,  6,  9],
       [ 1,  0,  9,  5],
       [ 4,  9, 13, 19],
       [ 8, 10,  1,  5]])

In [56]:
# number 6
data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np.array(data).flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])